require:
  - rubocop/rspec/focused

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
    - db/schema.rb

Rails:
  Enabled: true

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Rails/ActionFilter:
  EnforcedStyle: filter
  Enabled: true

Metrics/ParameterLists:
  Max: 11
  CountKeywordArgs: false

Metrics/LineLength:
  Max: 130
  Exclude:
    - 'config/**/*'

Metrics/CyclomaticComplexity:
  Max: 23

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - 'app/admin/**/*'
    - 'lib/tasks/**/*'

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/concerns/active_admin_shared/**/*'
    - 'db/migrate/**/*'

Style/Documentation:
  Enabled: false

Rails/Output:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Style/SpaceBeforeBlockBraces:
  Enabled: false

Style/IndentationConsistency:
  Enabled: false

Style/CaseIndentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/Lambda:
  Enabled: false

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Style/StructInheritance:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

NilComparison:
  Enabled: false
