require:
  - rubocop/rspec/focused

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'client/**/*'
    - db/schema.rb
    - db/seeds.rb
    - db/migrate/*

Rails:
  Enabled: true

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: brackets

Rails/ActionFilter:
  EnforcedStyle: action
  Enabled: true

Metrics/ParameterLists:
  Max: 11
  CountKeywordArgs: false

Metrics/LineLength:
  Max: 130
  Exclude:
    - 'config/**/*'

Metrics/CyclomaticComplexity:
  Max: 23

Metrics/AbcSize:
  Max: 40

Metrics/BlockLength:
  ExcludedMethods:
    - 'describe'
    - 'context'
    - 'draw'
    - 'setup'
    - 'resources'
    - 'resource'
    - 'route_param'
  Exclude:
    - 'app/admin/**/*'
    - 'lib/tasks/**/*'
    - 'spec/**/*'

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/concerns/active_admin_shared/**/*'
    - 'db/migrate/**/*'
  Max: 40

Style/Documentation:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Rails/Output:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: false

Layout/CaseIndentation:
  Enabled: false

Rails/HttpPositionalArguments:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Style/StructInheritance:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

NilComparison:
  Enabled: false
