smsc_login: 'delorub1'
smsc_password: 'e&^V8GAau@Jg#AU2'
smsc_api_url: 'https://smsc.ru/sys/send.php'

odnoklassniki_app_id: '1251484160'
odnoklassniki_app_public_key: 'CBADCJJLEBABABABA'
odnoklassniki_app_secret: '91A0DFC9B8E389F13F1489EB'

vkontakte_app_id: '6075628'
vkontakte_app_secret: 'Xb0QfdGTu0myb4MAGxph'

facebook_app_id: '161878731019435'
facebook_app_secret: '26f3e11a32ed00ee8e490e51b17a1b19'

development:
  yandex_kassa_url: 'https://demomoney.yandex.ru/eshop.xml'
  base_url: 'http://localhost:5000'
  shop_id: '155590'
  scid: '557653'
  shop_password: '67696hgjfgkr'
  base_url: 'http://localhost:5000'

staging:
  yandex_kassa_url: 'https://demomoney.yandex.ru/eshop.xml'
  base_url: 'https://new.delorub.ru'
  shop_id: '155590'
  scid: '557653'
  shop_password: '67696hgjfgkr'
  base_url: 'https://new.delorub.ru'

production:
  yandex_kassa_url: 'https://money.yandex.ru/eshop.xml'
  base_url: 'https://delorub.ru'
  shop_id: '155590'
  scid: '147953'
  shop_password: '67696hgjfgkr'
  base_url: 'https://delorub.ru'

test:
  shop_id: '155590'
  scid: '557653'
  shop_password: '67696hgjfgkr'
  base_url: 'http://localhost:5000'
