development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: delorub_development
  pool: 5
  username: delorub
  password:
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: delorub_production
  pool: 5
  username: delorub
  password:
  host: localhost
