default: &default
  url: redis://localhost:6379
  db: 0
development:
  <<: *default
staging:
  <<: *default
  db: 10
production:
  <<: *default
test:
  <<: *default
  db: 5
parser:
  <<: *default
  db: 5
