---
:verbose: true
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
development:
  :concurrency: 1
staging:
  :concurrency: 5
production:
  :concurrency: 10
:queues:
  - default
  - mailers
