# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_output_path: packs
  cache_path: tmp/cache/webpacker

  resolved_paths: []
  cache_manifest: false
  compile: false

  extensions:
    - .coffee
    - .erb
    - .js
    - .jsx
    - .ts
    - .vue
    - .sass
    - .scss
    - .css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

development:
  <<: *default

  dev_server:
    compile: false
    https: false
    host: localhost
    port: 8080
    https: false
    public: localhost:8080
    contentBase:
      - public
    inline: true
    overlay: true
    disable_host_check: true
    use_local_ip: false

test:
  <<: *default

  public_output_path: packs-test

production:
  <<: *default

staging:
  <<: *default
